# Generated by Django 2.2.6 on 2020-04-22 07:51

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cdp_audios',
            fields=[
                ('audio_id', models.AutoField(primary_key=True, serialize=False)),
                ('audio_title', models.CharField(max_length=520, verbose_name='Audio Title')),
                ('audio_description', ckeditor.fields.RichTextField(default='NA', max_length=2000, verbose_name='audio description')),
                ('audio_file', models.FileField(upload_to='media/chatou_auto/audio_files/')),
            ],
        ),
        migrations.CreateModel(
            name='cdp_Images',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('filename', models.ImageField(max_length=300, upload_to='media/chatou_auto/')),
                ('image_name', models.CharField(default='NA', max_length=1000, verbose_name='image name')),
                ('long_description', ckeditor.fields.RichTextField(default='NA', max_length=2000, verbose_name='long description')),
                ('short_description', ckeditor.fields.RichTextField(default='NA', max_length=2000, verbose_name='short description')),
            ],
        ),
        migrations.CreateModel(
            name='cdp_Itinerary',
            fields=[
                ('itinerary_id', models.AutoField(primary_key=True, serialize=False)),
                ('itinerary_name', models.CharField(max_length=520, verbose_name='Itinerary Name')),
                ('itinerary_steps', models.IntegerField(default=0, verbose_name='Itinerary Steps')),
                ('itinerary_type', models.CharField(choices=[('INTRO', 'INTRODUCTION'), ('ITIN', 'ITINERARY')], default='ITIN', max_length=520, verbose_name='Itinerary type')),
                ('is_visible_on_homepage', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='cdp_Map',
            fields=[
                ('page_id', models.AutoField(primary_key=True, serialize=False)),
                ('lat', models.CharField(max_length=520, verbose_name='lat')),
                ('longt', models.CharField(max_length=520, verbose_name='longt')),
            ],
        ),
        migrations.CreateModel(
            name='cdp_Map_Controls',
            fields=[
                ('MC_id', models.AutoField(primary_key=True, serialize=False)),
                ('zoom_for_home', models.DecimalField(decimal_places=1, default=15.0, max_digits=3, verbose_name='Zoom For Home')),
                ('pin_zoom', models.DecimalField(decimal_places=1, default=15.0, max_digits=3, verbose_name='Pin Zoom')),
            ],
        ),
        migrations.CreateModel(
            name='cdp_Page',
            fields=[
                ('page_id', models.AutoField(primary_key=True, serialize=False)),
                ('page_title', models.CharField(max_length=520, verbose_name='Page Title')),
                ('page_type', models.CharField(max_length=520, verbose_name='Page Type')),
                ('page_order', models.IntegerField(blank=True, null=True, verbose_name='Page Order')),
                ('page_Summary', models.CharField(default='NA', max_length=100000, verbose_name='Page Summary')),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commune_de_paris.cdp_Itinerary')),
            ],
        ),
        migrations.CreateModel(
            name='cdp_Page_Description',
            fields=[
                ('PD_id', models.AutoField(primary_key=True, serialize=False)),
                ('page_Text', ckeditor.fields.RichTextField(default='NA', max_length=100000, verbose_name='Page Text')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commune_de_paris.cdp_Page')),
                ('page_map', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='commune_de_paris.cdp_Map')),
                ('page_title_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='commune_de_paris.cdp_Images')),
            ],
        ),
        migrations.CreateModel(
            name='cdp_transport',
            fields=[
                ('transport_id', models.AutoField(primary_key=True, serialize=False)),
                ('transport_Details', models.CharField(max_length=520, verbose_name='transport Address')),
                ('transport_Comment', models.CharField(max_length=520, verbose_name='transport Comment')),
                ('Page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commune_de_paris.cdp_Page')),
            ],
        ),
        migrations.CreateModel(
            name='cdp_Toilets',
            fields=[
                ('Toilet_id', models.AutoField(primary_key=True, serialize=False)),
                ('Toilet_Address', models.CharField(max_length=520, verbose_name='Shopping Address')),
                ('Toilet_Comment', models.CharField(max_length=520, verbose_name='Shopping Comment')),
                ('Page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commune_de_paris.cdp_Page')),
            ],
        ),
        migrations.CreateModel(
            name='cdp_tickets',
            fields=[
                ('tickets_id', models.AutoField(primary_key=True, serialize=False)),
                ('tickets_Details', models.CharField(max_length=520, verbose_name='Tickets Address')),
                ('tickets_Comment', models.CharField(max_length=520, verbose_name='Tickets Comment')),
                ('Page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commune_de_paris.cdp_Page')),
            ],
        ),
        migrations.CreateModel(
            name='cdp_Shopping',
            fields=[
                ('Shopping_id', models.AutoField(primary_key=True, serialize=False)),
                ('Shopping_Address', models.CharField(max_length=520, verbose_name='Shopping Address')),
                ('Shopping_Comment', models.CharField(max_length=520, verbose_name='Shopping Comment')),
                ('Page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commune_de_paris.cdp_Page')),
            ],
        ),
        migrations.CreateModel(
            name='cdp_Resturant',
            fields=[
                ('Resturant_id', models.AutoField(primary_key=True, serialize=False)),
                ('Resturant_Address', models.CharField(max_length=520, verbose_name='Resturant Address')),
                ('Resturant_Comment', models.CharField(max_length=520, verbose_name='Resturant Comment')),
                ('Page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commune_de_paris.cdp_Page')),
            ],
        ),
        migrations.CreateModel(
            name='cdp_Page_Image_Order',
            fields=[
                ('PD_id', models.AutoField(primary_key=True, serialize=False)),
                ('appearnce_order', models.IntegerField(default=1, verbose_name='Appearnce Order')),
                ('is_page_present', models.BooleanField(default=True)),
                ('page_description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commune_de_paris.cdp_Page_Description')),
                ('page_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commune_de_paris.cdp_Images')),
            ],
        ),
        migrations.CreateModel(
            name='cdp_Page_Before_After_Image_Order',
            fields=[
                ('PD_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_page_in_present', models.BooleanField(default=True)),
                ('appearnce_order_in_page', models.IntegerField(default=1, verbose_name='Appearnce Order Page')),
                ('page_description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commune_de_paris.cdp_Page_Description')),
                ('page_image_after', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_after', to='commune_de_paris.cdp_Images')),
                ('page_image_before', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_before', to='commune_de_paris.cdp_Images')),
            ],
        ),
        migrations.CreateModel(
            name='cdp_opening_hours',
            fields=[
                ('oh_id', models.AutoField(primary_key=True, serialize=False)),
                ('oh_Details', models.CharField(max_length=520, verbose_name='Opening Hours Details')),
                ('oh_Comment', models.CharField(max_length=520, verbose_name='Opening Hours Comment')),
                ('Page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commune_de_paris.cdp_Page')),
            ],
        ),
        migrations.CreateModel(
            name='cdp_Menu',
            fields=[
                ('menu_id', models.AutoField(primary_key=True, serialize=False)),
                ('menu_title', models.CharField(max_length=520, verbose_name='Menu Title')),
                ('menu_link', models.CharField(max_length=520, verbose_name='Menu Link')),
                ('menu_type', models.CharField(max_length=520, verbose_name='Menu Type')),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commune_de_paris.cdp_Itinerary')),
                ('menu_images', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='commune_de_paris.cdp_Images')),
            ],
        ),
        migrations.AddField(
            model_name='cdp_map',
            name='Page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commune_de_paris.cdp_Page'),
        ),
        migrations.AddField(
            model_name='cdp_map',
            name='itinerary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commune_de_paris.cdp_Itinerary'),
        ),
        migrations.AddField(
            model_name='cdp_map',
            name='map_images',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='commune_de_paris.cdp_Images'),
        ),
        migrations.CreateModel(
            name='cdp_Lieu',
            fields=[
                ('Lieu_id', models.AutoField(primary_key=True, serialize=False)),
                ('Lieu_Address', models.CharField(max_length=520, verbose_name='Lieu Address')),
                ('Lieu_Comment', models.CharField(max_length=520, verbose_name='Lieu Comment')),
                ('Page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commune_de_paris.cdp_Page')),
            ],
        ),
        migrations.CreateModel(
            name='cdp_ITINERARY_Color_Scheme',
            fields=[
                ('ICS_id', models.AutoField(primary_key=True, serialize=False)),
                ('itinerary_colors', models.CharField(choices=[('BLUE', 'BLUE'), ('RED', 'RED')], default='BLUE', max_length=520, verbose_name='Itinerary colors')),
                ('itinerary', models.ForeignKey(blank=True, limit_choices_to={'itinerary_type': 'ITIN'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='commune_de_paris.cdp_Itinerary')),
            ],
        ),
        migrations.CreateModel(
            name='cdp_ChildrenEntertainment',
            fields=[
                ('CE_id', models.AutoField(primary_key=True, serialize=False)),
                ('CE_Address', models.CharField(max_length=520, verbose_name='CE Address')),
                ('CE_Comment', models.CharField(max_length=520, verbose_name='CE Comment')),
                ('Page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commune_de_paris.cdp_Page')),
            ],
        ),
        migrations.CreateModel(
            name='cdp_Burger_Menu_Ordering',
            fields=[
                ('BMO_id', models.AutoField(primary_key=True, serialize=False)),
                ('appearnce_order_in_burger_menu', models.IntegerField(default=1, verbose_name='Appearnce Order Burger Menu')),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commune_de_paris.cdp_Itinerary')),
                ('menu', models.ForeignKey(blank=True, limit_choices_to={'menu_type': 'Burger'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='commune_de_paris.cdp_Menu')),
            ],
        ),
        migrations.CreateModel(
            name='cdp_Bar',
            fields=[
                ('Bar_id', models.AutoField(primary_key=True, serialize=False)),
                ('Bar_Address', models.CharField(max_length=520, verbose_name='Bar Address')),
                ('Bar_Comment', models.CharField(max_length=520, verbose_name='Bar Comment')),
                ('Page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commune_de_paris.cdp_Page')),
            ],
        ),
        migrations.CreateModel(
            name='cdp_audio_page',
            fields=[
                ('ap_id', models.AutoField(primary_key=True, serialize=False)),
                ('audio_appearnce_order', models.IntegerField(default=1, verbose_name='Audio Appearnce Order')),
                ('is_audio_present_on_page', models.BooleanField(default=True)),
                ('audio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commune_de_paris.cdp_audios')),
                ('page_description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commune_de_paris.cdp_Page_Description')),
            ],
        ),
    ]
