# Generated by Django 2.2.6 on 2020-04-23 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commune_de_paris', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cdp_audios',
            name='audio_file',
            field=models.FileField(upload_to='media/commune_de_paris/audio_files/'),
        ),
        migrations.AlterField(
            model_name='cdp_images',
            name='filename',
            field=models.ImageField(max_length=300, upload_to='media/communde_de_paris/'),
        ),
    ]
