# Generated by Django 2.2.6 on 2020-04-25 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commune_de_paris', '0003_auto_20200424_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='cdp_map',
            name='geo_coordinates',
            field=models.CharField(blank=True, max_length=520, null=True, verbose_name='Geo Coordinates (latitude,longitude)'),
        ),
    ]
