# Generated by Django 2.2.6 on 2020-05-26 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commune_de_paris', '0004_cdp_map_geo_coordinates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cdp_itinerary',
            name='itinerary_type',
            field=models.CharField(choices=[('INTRO', 'INTRODUCTION'), ('ITIN', 'ITINERARY'), ('ITIN_INDEX', 'ITINERARY_INDEX')], default='ITIN', max_length=520, verbose_name='Itinerary type'),
        ),
    ]
