# Generated by Django 2.2.6 on 2020-06-22 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commune_de_paris', '0007_cdp_images_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cdp_page',
            name='page_type',
            field=models.CharField(choices=[('step', 'step'), ('step_index', 'step_index'), ('step_introduction', 'step_introduction'), ('step_introduction_index', 'step_introduction_index'), ('introduction', 'introduction')], default='step', max_length=520, verbose_name='Page Type'),
        ),
    ]
