# Generated by Django 2.2.6 on 2020-06-22 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commune_de_paris', '0009_cdp_page_is_page_zero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cdp_page',
            name='is_page_zero',
            field=models.BooleanField(default=False),
        ),
    ]
