# Generated by Django 2.2.6 on 2020-09-08 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commune_de_paris', '0010_auto_20200622_0208'),
    ]

    operations = [
        migrations.AddField(
            model_name='cdp_page',
            name='page_display_title',
            field=models.CharField(default='', max_length=520, verbose_name='Page Title'),
        ),
        migrations.AddField(
            model_name='cdp_page',
            name='show_display_title',
            field=models.BooleanField(default=False),
        ),
    ]
