# Generated by Django 2.2.6 on 2020-09-08 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commune_de_paris', '0011_auto_20200908_0225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cdp_page',
            name='page_display_title',
            field=models.CharField(default='', max_length=520, null=True, verbose_name='Page Display Title'),
        ),
    ]
