# Generated by Django 2.2.6 on 2020-02-19 15:06

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatou_auto', '0002_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('filename', models.ImageField(upload_to='media/chatou_auto/')),
                ('image_name', models.CharField(max_length=1000, verbose_name='image name')),
                ('long_description', ckeditor.fields.RichTextField(max_length=2000, verbose_name='long description')),
                ('short_description', ckeditor.fields.RichTextField(max_length=2000, verbose_name='short description')),
            ],
        ),
    ]
