# Generated by Django 2.2.6 on 2020-02-23 16:28

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatou_auto', '0004_auto_20200222_0715'),
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('page_id', models.AutoField(primary_key=True, serialize=False)),
                ('lat', models.CharField(max_length=520, verbose_name='lat')),
                ('longt', models.CharField(max_length=520, verbose_name='longt')),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('page_id', models.AutoField(primary_key=True, serialize=False)),
                ('page_title', models.CharField(max_length=520, verbose_name='Page Title')),
                ('page_type', models.CharField(max_length=520, verbose_name='Menu Type')),
                ('page_order', models.IntegerField(blank=True, null=True, verbose_name='Page Order')),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatou_auto.Itinerary')),
            ],
        ),
        migrations.CreateModel(
            name='Shopping',
            fields=[
                ('Shopping_id', models.AutoField(primary_key=True, serialize=False)),
                ('Shopping_Address', models.CharField(max_length=520, verbose_name='Shopping Address')),
                ('Shopping_Comment', models.CharField(max_length=520, verbose_name='Shopping Comment')),
                ('Page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatou_auto.Page')),
            ],
        ),
        migrations.CreateModel(
            name='Resturant',
            fields=[
                ('Resturant_id', models.AutoField(primary_key=True, serialize=False)),
                ('Resturant_Address', models.CharField(max_length=520, verbose_name='Resturant Address')),
                ('Resturant_Comment', models.CharField(max_length=520, verbose_name='Resturant Comment')),
                ('Page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatou_auto.Page')),
            ],
        ),
        migrations.CreateModel(
            name='Page_Description',
            fields=[
                ('PD_id', models.AutoField(primary_key=True, serialize=False)),
                ('page_Text', ckeditor.fields.RichTextField(default='NA', max_length=10000, verbose_name='Page Text')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatou_auto.Page')),
                ('page_map', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='chatou_auto.Map')),
                ('page_title_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='chatou_auto.Images')),
            ],
        ),
        migrations.AddField(
            model_name='map',
            name='Page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatou_auto.Page'),
        ),
        migrations.AddField(
            model_name='map',
            name='itinerary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatou_auto.Itinerary'),
        ),
        migrations.AddField(
            model_name='map',
            name='map_images',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='chatou_auto.Images'),
        ),
        migrations.CreateModel(
            name='Lieu',
            fields=[
                ('Lieu_id', models.AutoField(primary_key=True, serialize=False)),
                ('Lieu_Address', models.CharField(max_length=520, verbose_name='Lieu Address')),
                ('Lieu_Comment', models.CharField(max_length=520, verbose_name='Lieu Comment')),
                ('Page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatou_auto.Page')),
            ],
        ),
        migrations.CreateModel(
            name='ChildrenEntertainment',
            fields=[
                ('CE_id', models.AutoField(primary_key=True, serialize=False)),
                ('CE_Address', models.CharField(max_length=520, verbose_name='CE Address')),
                ('CE_Comment', models.CharField(max_length=520, verbose_name='CE Comment')),
                ('Page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatou_auto.Page')),
            ],
        ),
        migrations.CreateModel(
            name='Bar',
            fields=[
                ('Bar_id', models.AutoField(primary_key=True, serialize=False)),
                ('Bar_Address', models.CharField(max_length=520, verbose_name='Bar Address')),
                ('Bar_Comment', models.CharField(max_length=520, verbose_name='Bar Comment')),
                ('Page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatou_auto.Page')),
            ],
        ),
    ]
