# Generated by Django 2.2.6 on 2020-02-23 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatou_auto', '0005_auto_20200223_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page_description',
            name='page_map',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='chatou_auto.Map'),
        ),
    ]
