# Generated by Django 2.2.6 on 2020-02-24 13:40

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatou_auto', '0007_auto_20200224_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page_description',
            name='page_Text',
            field=ckeditor.fields.RichTextField(default='NA', max_length=100000, verbose_name='Page Text'),
        ),
    ]
