# Generated by Django 2.2.6 on 2020-02-27 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatou_auto', '0008_auto_20200224_1340'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page_Image_Order',
            fields=[
                ('PD_id', models.AutoField(primary_key=True, serialize=False)),
                ('appearnce_order', models.IntegerField(default=2, verbose_name='Appearnce Order')),
                ('page_description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatou_auto.Page_Description')),
                ('page_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatou_auto.Images')),
            ],
        ),
    ]
