# Generated by Django 2.2.6 on 2020-02-27 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatou_auto', '0009_page_image_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page_image_order',
            name='appearnce_order',
            field=models.IntegerField(default=1, verbose_name='Appearnce Order'),
        ),
    ]
