# Generated by Django 2.2.6 on 2020-02-29 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatou_auto', '0010_auto_20200227_1825'),
    ]

    operations = [
        migrations.CreateModel(
            name='Toilets',
            fields=[
                ('Toilet_id', models.AutoField(primary_key=True, serialize=False)),
                ('Toilet_Address', models.CharField(max_length=520, verbose_name='Shopping Address')),
                ('Toilet_Comment', models.CharField(max_length=520, verbose_name='Shopping Comment')),
                ('Page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatou_auto.Page')),
            ],
        ),
    ]
