# Generated by Django 2.2.6 on 2020-03-03 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatou_auto', '0011_toilets'),
    ]

    operations = [
        migrations.AddField(
            model_name='page_image_order',
            name='is_page_present',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Page_Before_After_Image_Order',
            fields=[
                ('PD_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_page_in_present', models.BooleanField(default=True)),
                ('appearnce_order_in_page', models.IntegerField(default=1, verbose_name='Appearnce Order Page')),
                ('page_description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatou_auto.Page_Description')),
                ('page_image_after', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_after', to='chatou_auto.Images')),
                ('page_image_before', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_before', to='chatou_auto.Images')),
            ],
        ),
    ]
