# Generated by Django 2.2.6 on 2020-03-11 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatou_auto', '0012_auto_20200303_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='itinerary_type',
            field=models.CharField(choices=[('INTRO', 'INTRODUCTION'), ('ITIN', 'ITINERARY')], default='ITIN', max_length=520, verbose_name='Itinerary type'),
        ),
    ]
