# Generated by Django 2.2.6 on 2020-03-12 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatou_auto', '0014_page_page_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='page_Summary',
            field=models.CharField(default='NA', max_length=100000, verbose_name='Page Summary'),
        ),
    ]
