# Generated by Django 2.2.6 on 2020-03-16 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatou_auto', '0015_auto_20200312_0751'),
    ]

    operations = [
        migrations.CreateModel(
            name='Burger_Menu_Ordering',
            fields=[
                ('BMO_id', models.AutoField(primary_key=True, serialize=False)),
                ('appearnce_order_in_burger_menu', models.IntegerField(default=1, verbose_name='Appearnce Order Burger Menu')),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatou_auto.Itinerary')),
                ('menu', models.ForeignKey(blank=True, limit_choices_to={'menu_type': 'burger'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='chatou_auto.Menu')),
            ],
        ),
    ]
