# Generated by Django 2.2.6 on 2020-03-16 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatou_auto', '0016_burger_menu_ordering'),
    ]

    operations = [
        migrations.AlterField(
            model_name='burger_menu_ordering',
            name='menu',
            field=models.ForeignKey(blank=True, limit_choices_to={'menu_type': 'Burger'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='chatou_auto.Menu'),
        ),
    ]
