# Generated by Django 2.2.6 on 2020-03-24 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatou_auto', '0017_auto_20200316_0209'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='is_visible_on_homepage',
            field=models.BooleanField(default=True),
        ),
    ]
