# Generated by Django 2.2.6 on 2020-03-25 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatou_auto', '0018_itinerary_is_visible_on_homepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ITINERARY_Color_Scheme',
            fields=[
                ('ICS_id', models.AutoField(primary_key=True, serialize=False)),
                ('itinerary_colors', models.CharField(choices=[('BLUE', 'BLUE'), ('RED', 'RED')], default='BLUE', max_length=520, verbose_name='Itinerary colors')),
                ('itinerary', models.ForeignKey(blank=True, limit_choices_to={'itinerary_type': 'ITIN'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='chatou_auto.Itinerary')),
            ],
        ),
    ]
