# Generated by Django 2.2.6 on 2020-04-03 17:19

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatou_auto', '0019_itinerary_color_scheme'),
    ]

    operations = [
        migrations.CreateModel(
            name='audios',
            fields=[
                ('audio_id', models.AutoField(primary_key=True, serialize=False)),
                ('audio_description', ckeditor.fields.RichTextField(default='NA', max_length=2000, verbose_name='audio description')),
                ('audio_title', models.CharField(max_length=520, verbose_name='Itinerary colors')),
                ('audio_file', models.FileField(upload_to='media/chatou_auto/audio_files/')),
            ],
        ),
    ]
