# Generated by Django 2.2.6 on 2020-04-03 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatou_auto', '0020_audios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audios',
            name='audio_title',
            field=models.CharField(max_length=520, verbose_name='Audio Title'),
        ),
    ]
