# Generated by Django 2.2.6 on 2020-04-03 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatou_auto', '0021_auto_20200403_1837'),
    ]

    operations = [
        migrations.CreateModel(
            name='audio_page',
            fields=[
                ('ap_id', models.AutoField(primary_key=True, serialize=False)),
                ('audio_appearnce_order', models.IntegerField(default=1, verbose_name='Audio Appearnce Order')),
                ('is_audio_present_on_page', models.BooleanField(default=True)),
                ('audio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatou_auto.audios')),
                ('page_description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatou_auto.Page_Description')),
            ],
        ),
    ]
