# Generated by Django 2.2.6 on 2020-04-11 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatou_auto', '0022_audio_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='Map_Controls',
            fields=[
                ('MC_id', models.AutoField(primary_key=True, serialize=False)),
                ('zoom_for_home', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Zoom For Home')),
                ('pin_zoom', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Pin Zoom')),
            ],
        ),
    ]
