# Generated by Django 2.2.6 on 2020-04-11 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatou_auto', '0023_map_controls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map_controls',
            name='pin_zoom',
            field=models.DecimalField(decimal_places=1, default=15.0, max_digits=3, verbose_name='Pin Zoom'),
        ),
        migrations.AlterField(
            model_name='map_controls',
            name='zoom_for_home',
            field=models.DecimalField(decimal_places=1, default=15.0, max_digits=3, verbose_name='Zoom For Home'),
        ),
    ]
