# Generated by Django 2.2.6 on 2020-04-17 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatou_auto', '0024_auto_20200411_0139'),
    ]

    operations = [
        migrations.CreateModel(
            name='transport',
            fields=[
                ('transport_id', models.AutoField(primary_key=True, serialize=False)),
                ('transport_Details', models.CharField(max_length=520, verbose_name='transport Address')),
                ('transport_Comment', models.CharField(max_length=520, verbose_name='transport Comment')),
                ('Page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatou_auto.Page')),
            ],
        ),
        migrations.CreateModel(
            name='tickets',
            fields=[
                ('tickets_id', models.AutoField(primary_key=True, serialize=False)),
                ('tickets_Details', models.CharField(max_length=520, verbose_name='Tickets Address')),
                ('tickets_Comment', models.CharField(max_length=520, verbose_name='Tickets Comment')),
                ('Page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatou_auto.Page')),
            ],
        ),
        migrations.CreateModel(
            name='opening_hours',
            fields=[
                ('oh_id', models.AutoField(primary_key=True, serialize=False)),
                ('oh_Details', models.CharField(max_length=520, verbose_name='Opening Hours Details')),
                ('oh_Comment', models.CharField(max_length=520, verbose_name='Opening Hours Comment')),
                ('Page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatou_auto.Page')),
            ],
        ),
    ]
