# Generated by Django 2.2.6 on 2020-04-25 08:57

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatou_auto', '0025_opening_hours_tickets_transport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bar',
            name='Bar_Address',
        ),
        migrations.RemoveField(
            model_name='bar',
            name='Bar_Comment',
        ),
        migrations.RemoveField(
            model_name='childrenentertainment',
            name='CE_Address',
        ),
        migrations.RemoveField(
            model_name='childrenentertainment',
            name='CE_Comment',
        ),
        migrations.RemoveField(
            model_name='lieu',
            name='Lieu_Address',
        ),
        migrations.RemoveField(
            model_name='lieu',
            name='Lieu_Comment',
        ),
        migrations.RemoveField(
            model_name='opening_hours',
            name='oh_Comment',
        ),
        migrations.RemoveField(
            model_name='opening_hours',
            name='oh_Details',
        ),
        migrations.RemoveField(
            model_name='resturant',
            name='Resturant_Address',
        ),
        migrations.RemoveField(
            model_name='resturant',
            name='Resturant_Comment',
        ),
        migrations.RemoveField(
            model_name='shopping',
            name='Shopping_Address',
        ),
        migrations.RemoveField(
            model_name='shopping',
            name='Shopping_Comment',
        ),
        migrations.RemoveField(
            model_name='tickets',
            name='tickets_Comment',
        ),
        migrations.RemoveField(
            model_name='tickets',
            name='tickets_Details',
        ),
        migrations.RemoveField(
            model_name='toilets',
            name='Toilet_Address',
        ),
        migrations.RemoveField(
            model_name='toilets',
            name='Toilet_Comment',
        ),
        migrations.RemoveField(
            model_name='transport',
            name='transport_Comment',
        ),
        migrations.RemoveField(
            model_name='transport',
            name='transport_Details',
        ),
        migrations.AddField(
            model_name='bar',
            name='Bar_Description',
            field=ckeditor.fields.RichTextField(blank=True, max_length=2000, null=True, verbose_name='Bar Description'),
        ),
        migrations.AddField(
            model_name='childrenentertainment',
            name='CE_Description',
            field=ckeditor.fields.RichTextField(blank=True, max_length=2000, null=True, verbose_name='CE Description'),
        ),
        migrations.AddField(
            model_name='lieu',
            name='Lieu_Description',
            field=ckeditor.fields.RichTextField(blank=True, max_length=2000, null=True, verbose_name='Lieu Description'),
        ),
        migrations.AddField(
            model_name='opening_hours',
            name='oh_Description',
            field=ckeditor.fields.RichTextField(blank=True, max_length=2000, null=True, verbose_name='oh Description'),
        ),
        migrations.AddField(
            model_name='resturant',
            name='Resturant_Description',
            field=ckeditor.fields.RichTextField(blank=True, max_length=2000, null=True, verbose_name='Resturant Description'),
        ),
        migrations.AddField(
            model_name='shopping',
            name='Shopping_Description',
            field=ckeditor.fields.RichTextField(blank=True, max_length=2000, null=True, verbose_name='Shopping Description'),
        ),
        migrations.AddField(
            model_name='tickets',
            name='tickets_Description',
            field=ckeditor.fields.RichTextField(blank=True, max_length=2000, null=True, verbose_name='tickets Description'),
        ),
        migrations.AddField(
            model_name='toilets',
            name='Toilet_Description',
            field=ckeditor.fields.RichTextField(blank=True, max_length=2000, null=True, verbose_name='Toilet Description'),
        ),
        migrations.AddField(
            model_name='transport',
            name='transport_Description',
            field=ckeditor.fields.RichTextField(blank=True, max_length=2000, null=True, verbose_name='transport Description'),
        ),
    ]
